--Problem 1 - DDL
CREATE DATABASE ReportService
GO
USE ReportService
GO

CREATE TABLE Users
(
	Id INT IDENTITY NOT NULL,
	Username NVARCHAR(30) UNIQUE NOT NULL,
	Password NVARCHAR(50) NOT NULL,
	Name NVARCHAR(50),
	Gender CHAR(1),
	BirthDate DATETIME,
	Age INT,
	Email NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Users PRIMARY KEY (Id),
	CONSTRAINT CK_Users_Gender CHECK(Gender IN ('M','F'))
)

CREATE TABLE Departments
(
	Id INT IDENTITY NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Departments PRIMARY KEY (Id)
)

CREATE TABLE Employees
(
	Id INT IDENTITY NOT NULL,
	FirstName NVARCHAR(25),
	LastName NVARCHAR(25),
	Gender CHAR(1),
	BirthDate DATETIME,
	Age INT,
	DepartmentId INT NOT NULL,
	CONSTRAINT PK_Employees PRIMARY KEY (Id),
	CONSTRAINT FK_Employees_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments(Id),
	CONSTRAINT CK_Employees_Gender CHECK(Gender IN ('M','F'))
)

CREATE TABLE Categories
(
	Id INT IDENTITY NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	DepartmentId INT NOT NULL,
	CONSTRAINT PK_Categories PRIMARY KEY (Id),
	CONSTRAINT FK_Categories_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)
)

CREATE TABLE Status
(
	Id INT IDENTITY NOT NULL,
	Label NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_Status PRIMARY KEY (Id)
)

CREATE TABLE Reports
(
	Id INT IDENTITY NOT NULL,
	CategoryId INT NOT NULL,
	StatusId INT NOT NULL,
	OpenDate DATETIME NOT NULL,
	CloseDate DATETIME,
	Description NVARCHAR(200),
	UserId INT NOT NULL,
	EmployeeId INT,
	CONSTRAINT PK_Reports PRIMARY KEY (Id),
	CONSTRAINT FK_Report_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
	CONSTRAINT FK_Report_Status FOREIGN KEY (StatusId) REFERENCES Status(Id),
	CONSTRAINT FK_Report_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
	CONSTRAINT FK_Report_Employees FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
)